name: Node.js CI

on:
  push:
    branches: [master, feat/github-actions]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x, 18.x, 20.x]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm test

  coverage:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run test-coverage
      - run: npm run test-coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@v2
